services:
  db:
    container_name: serv_postgres_cn
    hostname: serv_postgres
    image: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: jobmanagement_db
    ports:
      - "5432:5432"
    networks:
      vnet_inf210:
        ipv4_address: 10.5.0.8
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./Data/SQL_Scripts/create_db_jobmanagement.sql:/docker-entrypoint-initdb.d/01_create_db_jobmanagement.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d jobmanagement_db"]
      interval: 10s
      timeout: 5s
      retries: 5
   
       
  pgadmin:
    container_name: pgadmin4_cn
    hostname: serv_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgpwd
    ports:
      - "5051:80"
    networks:
      vnet_inf210:
        ipv4_address: 10.5.0.7
    volumes: 
      - ./Data/CNX/servers.json:/pgadmin4/servers.json
      - ./Data/CNX/pass:/pgadmin4/pgpass
    depends_on:
      - "db"

networks:
  vnet_inf210:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16

volumes:
  postgres_data: